In [1]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame

### Removing duplicates

In [2]:
%pip list

Package                   Version
------------------------- -----------
anyio                     4.12.1
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.1
async-lru                 2.2.0
attrs                     25.4.0
babel                     2.18.0
beautifulsoup4            4.14.3
bleach                    6.3.0
certifi                   2026.2.25
cffi                      2.0.0
charset-normalizer        3.4.5
colorama                  0.4.6
comm                      0.2.3
debugpy                   1.8.20
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.1
fastjsonschema            2.21.2
fqdn                      1.5.1
gitdb                     4.0.12
GitPython                 3.1.46
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.11
ipykernel                 7.2.0
ipython                   9.11.0
ipython_pygments_lexers   1.1.1
isoduration               20.11.0
jedi                      0.19.2
Jinja2                    3.1.6
json5                     0.13.0
jsonpointer               3.0.0
jsonschema                4.26.0
jsonschema-specifications 2025.9.1
jupyter_client            8.8.0
jupyter_core              5.9.1
jupyter-events            0.12.0
jupyter-lsp               2.3.0
jupyter_server            2.17.0
jupyter_server_terminals  0.5.4
jupyterlab                4.5.5
jupyterlab_git            0.52.0
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
lark                      1.3.1
MarkupSafe                3.0.3
matplotlib-inline         0.2.1
mistune                   3.2.0
nbclient                  0.10.4
nbconvert                 7.17.0
nbdime                    4.0.4
nbformat                  5.10.4
nest-asyncio              1.6.0
notebook_shim             0.2.4
numpy                     2.4.6
packaging                 26.0
pandas                    3.0.3
pandocfilters             1.5.1
parso                     0.8.6
pexpect                   4.9.0
pip                       26.1.1
platformdirs              4.9.4
prometheus_client         0.24.1
prompt_toolkit            3.0.52
psutil                    7.2.2
ptyprocess                0.7.0
pure_eval                 0.2.3
pycparser                 3.0
Pygments                  2.19.2
python-dateutil           2.9.0.post0
python-json-logger        4.0.0
PyYAML                    6.0.3
pyzmq                     27.1.0
referencing               0.37.0
requests                  2.32.5
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rpds-py                   0.30.0
Send2Trash                2.1.0
setuptools                82.0.1
six                       1.17.0
smmap                     5.0.3
soupsieve                 2.8.3
stack-data                0.6.3
terminado                 0.18.1
tinycss2                  1.4.0
tornado                   6.5.5
traitlets                 5.14.3
typing_extensions         4.15.0
tzdata                    2025.3
uri-template              1.3.0
urllib3                   2.6.3
wcwidth                   0.6.0
webcolors                 25.10.0
webencodings              0.5.1
websocket-client          1.9.0
Note: you may need to restart the kernel to use updated packages.

In [10]:
df_obj = DataFrame({'column 1': [1,1,2,3,3,3,3],
                    'column 2': ['a', 'a', 'b', 'b', 'c', 'c', 'c'],
                    'column 3': ['A', 'A', 'B', 'B', 'C', 'D', 'C']})

df_obj

   column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         3        b        B
4         3        c        C
5         3        c        D
6         3        c        C

In [9]:
df_obj.duplicated()

0    False
1     True
2    False
3    False
4    False
5     True
6     True
dtype: bool

In [11]:
df_obj.drop_duplicates(['column 3'])

   column 1 column 2 column 3
0         1        a        A
2         2        b        B
4         3        c        C
5         3        c        D